# Generated by Django 5.2 on 2025-04-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimodel',
            old_name='version',
            new_name='runtime',
        ),
    ]
