# Generated by Django 5.2 on 2025-04-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0002_rename_version_aimodel_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='architecture',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='runtime',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='accuraccy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
