# Generated by Django 4.2.19 on 2025-04-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0002_rename_version_aimodel_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='architecture',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='runtime',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
