# Generated by Django 5.2 on 2025-04-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0004_alter_aimodel_parameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimodel',
            old_name='accuraccy',
            new_name='accuracy',
        ),
    ]
