# Generated by Django 4.2.19 on 2025-04-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0005_rename_accuraccy_aimodel_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='parameters',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
