# Generated by Django 5.2 on 2025-04-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0007_remove_aimodel_accuracy_alter_aimodel_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='qualcomm_link',
            field=models.CharField(default='temp', max_length=255, unique=False),
            preserve_default=False,
        ),
    ]
