# Generated by Django 5.2 on 2025-04-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0008_aimodel_qualcomm_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='qualcomm_link',
            field=models.CharField(max_length=255),
        ),
    ]
