# Generated by Django 5.2 on 2025-04-18 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0009_alter_aimodel_qualcomm_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='qualcomm_link',
        ),
    ]
