# Generated by Django 5.2 on 2025-04-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0012_remove_aimodel_qualcomm_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='qualcomm_link',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
    ]
